{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "2137c645",
   "metadata": {},
   "source": [
    "# Pettingzoo inside ray"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1ca4855e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pettingzoo.mpe import simple_tag_v2\n",
    "from pettingzoo.test import render_test\n",
    "from pettingzoo.test import performance_benchmark\n",
    "from pettingzoo.test import test_save_obs\n",
    "import ray\n",
    "\n",
    "import time\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7569daa7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "adversary_0\n",
      "[ 0.          0.         -0.81671894 -0.35830274  0.7397504   0.87728226\n",
      "  0.24053054 -0.3338143   0.4263175  -0.13701786  1.0103662  -0.5890981\n",
      "  0.5039304   0.7280103   0.          0.        ] 0.0 False False {}\n",
      "adversary_1\n",
      "[ 0.          0.         -0.39040145 -0.4953206   0.3134329   1.0143001\n",
      " -0.18578696 -0.19679645 -0.4263175   0.13701786  0.58404875 -0.45208025\n",
      "  0.07761288  0.86502814  0.          0.        ] 0.0 False False {}\n",
      "adversary_2\n",
      "[ 0.          0.          0.19364728 -0.94740087 -0.27061585  1.4663804\n",
      " -0.7698357   0.2552838  -1.0103662   0.5890981  -0.58404875  0.45208025\n",
      " -0.5064359   1.3171084   0.          0.        ] 0.0 False False {}\n",
      "agent_0\n",
      "[ 0.          0.         -0.31278858  0.36970752  0.23582003  0.14927197\n",
      " -0.26339984 -1.0618246  -0.5039304  -0.7280103  -0.07761288 -0.86502814\n",
      "  0.5064359  -1.3171084 ] 0.0 False False {}\n"
     ]
    }
   ],
   "source": [
    "cycles = 1\n",
    "agent_count = 4\n",
    "current_cycle = 0\n",
    "action_queue = []\n",
    "\n",
    "env = simple_tag_v2.env(render_mode=\"rgb_array\", max_cycles=cycles)\n",
    "env.reset()\n",
    "for agent in env.agent_iter():\n",
    "    if current_cycle >= cycles * agent_count:\n",
    "        break\n",
    "    if current_cycle % agent_count == 0:\n",
    "        adversary_0_action = random.choice([0, 1, 2, 3, 4])\n",
    "        adversary_1_action = random.choice([0, 1, 2, 3, 4])\n",
    "        adversary_2_action = random.choice([0, 1, 2, 3, 4])\n",
    "        good_agent_action = random.choice([0, 1, 2, 3, 4])\n",
    "\n",
    "        action_queue += [\n",
    "            adversary_0_action,\n",
    "            adversary_1_action,\n",
    "            adversary_2_action,\n",
    "            good_agent_action\n",
    "        ]\n",
    "    print(agent)\n",
    "    env.render()\n",
    "    # obs, reward, done, info = env.last()\n",
    "    observation, cumulative_rewards, terminations, truncations, infos = env.last()\n",
    "    print(observation, cumulative_rewards, terminations, truncations, infos)\n",
    "    action = action_queue.pop(0)\n",
    "    env.step(action)\n",
    "    current_cycle += 1\n",
    "else:\n",
    "    env.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c79e8b07",
   "metadata": {},
   "source": [
    "## info"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "be4f3124",
   "metadata": {},
   "source": [
    "`observation, cumulative_rewards, terminations, truncations, infos = env.last()`\n",
    "\n",
    "examples of the above returned values:\n",
    "\n",
    "`observation = [ 0.          0.         -0.81671894 -0.35830274  0.7397504   0.87728226  0.24053054 -0.3338143   0.4263175 -0.13701786  1.0103662  -0.5890981 0.5039304   0.7280103   0.          0.        ]`\n",
    "\n",
    "observations are ordered like this:\n",
    "\n",
    "`[self_vel, self_pos, landmark_rel_positions[..], other_agent_rel_positions[..], other_agent_velocities[..]]`\n",
    "\n",
    "`cumulative_rewards = 0.0`\n",
    "\n",
    "`terminations = False `\n",
    "\n",
    "`truncations = False `\n",
    "\n",
    "`infos = {}`\n",
    "\n",
    "\n",
    "then for agent names and actions, they are:\n",
    "\n",
    "\n",
    "`agent names: adversary_0, adversary_1 ..., agent_0`\n",
    "\n",
    "`actions: 0, 1, 2, 3 or 4 (meaning no_action, move_left, move_right, move_down, move_up)`"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9471f526",
   "metadata": {},
   "source": [
    "# Original testing code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b458a733",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Approximate pi using random sampling. Generate x and y randomly between 0 and 1. \n",
    "#  if x^2 + y^2 < 1 it's inside the quarter circle. x 4 to get pi. \n",
    "import ray\n",
    "from random import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b5bfcbe7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:06:51,306\tINFO worker.py:1553 -- Started a local Ray instance.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.141644 is an approximation of pi\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 30\u001b[0m\n\u001b[0;32m     28\u001b[0m results \u001b[38;5;241m=\u001b[39m [] \n\u001b[0;32m     29\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m _ \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(BATCHES):\n\u001b[1;32m---> 30\u001b[0m     results\u001b[38;5;241m.\u001b[39mappend(\u001b[43mpi4_sample\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mremote\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[0;32m     31\u001b[0m output \u001b[38;5;241m=\u001b[39m ray\u001b[38;5;241m.\u001b[39mget(results)\n\u001b[0;32m     32\u001b[0m pi \u001b[38;5;241m=\u001b[39m \u001b[38;5;28msum\u001b[39m(output) \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m4.0\u001b[39m \u001b[38;5;241m/\u001b[39m BATCHES \u001b[38;5;241m/\u001b[39m SAMPLES\n",
      "File \u001b[1;32mD:\\Study_Documents\\thesis\\env\\lib\\site-packages\\ray\\remote_function.py:129\u001b[0m, in \u001b[0;36mRemoteFunction.__init__.<locals>._remote_proxy\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    127\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(function)\n\u001b[0;32m    128\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_remote_proxy\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m--> 129\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_remote(args\u001b[38;5;241m=\u001b[39margs, kwargs\u001b[38;5;241m=\u001b[39mkwargs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_default_options)\n",
      "File \u001b[1;32mD:\\Study_Documents\\thesis\\env\\lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py:307\u001b[0m, in \u001b[0;36m_tracing_task_invocation.<locals>._invocation_remote_span\u001b[1;34m(self, args, kwargs, *_args, **_kwargs)\u001b[0m\n\u001b[0;32m    305\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m kwargs \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    306\u001b[0m         \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_ray_trace_ctx\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m kwargs\n\u001b[1;32m--> 307\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m method(\u001b[38;5;28mself\u001b[39m, args, kwargs, \u001b[38;5;241m*\u001b[39m_args, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39m_kwargs)\n\u001b[0;32m    309\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_ray_trace_ctx\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m kwargs\n\u001b[0;32m    311\u001b[0m tracer \u001b[38;5;241m=\u001b[39m _opentelemetry\u001b[38;5;241m.\u001b[39mtrace\u001b[38;5;241m.\u001b[39mget_tracer(\u001b[38;5;18m__name__\u001b[39m)\n",
      "File \u001b[1;32mD:\\Study_Documents\\thesis\\env\\lib\\site-packages\\ray\\remote_function.py:412\u001b[0m, in \u001b[0;36mRemoteFunction._remote\u001b[1;34m(self, args, kwargs, **task_options)\u001b[0m\n\u001b[0;32m    409\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_decorator \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    410\u001b[0m     invocation \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_decorator(invocation)\n\u001b[1;32m--> 412\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43minvocation\u001b[49m\u001b[43m(\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mD:\\Study_Documents\\thesis\\env\\lib\\site-packages\\ray\\remote_function.py:387\u001b[0m, in \u001b[0;36mRemoteFunction._remote.<locals>.invocation\u001b[1;34m(args, kwargs)\u001b[0m\n\u001b[0;32m    383\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m worker\u001b[38;5;241m.\u001b[39mmode \u001b[38;5;241m==\u001b[39m ray\u001b[38;5;241m.\u001b[39m_private\u001b[38;5;241m.\u001b[39mworker\u001b[38;5;241m.\u001b[39mLOCAL_MODE:\n\u001b[0;32m    384\u001b[0m     \u001b[38;5;28;01massert\u001b[39;00m (\n\u001b[0;32m    385\u001b[0m         \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_is_cross_language\n\u001b[0;32m    386\u001b[0m     ), \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCross language remote function cannot be executed locally.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m--> 387\u001b[0m object_refs \u001b[38;5;241m=\u001b[39m \u001b[43mworker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcore_worker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msubmit_task\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    388\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_language\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    389\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_function_descriptor\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    390\u001b[0m \u001b[43m    \u001b[49m\u001b[43mlist_args\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    391\u001b[0m \u001b[43m    \u001b[49m\u001b[43mname\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mis\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    392\u001b[0m \u001b[43m    \u001b[49m\u001b[43mnum_returns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    393\u001b[0m \u001b[43m    \u001b[49m\u001b[43mresources\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    394\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    395\u001b[0m \u001b[43m    \u001b[49m\u001b[43mretry_exceptions\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    396\u001b[0m \u001b[43m    \u001b[49m\u001b[43mretry_exception_allowlist\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    397\u001b[0m \u001b[43m    \u001b[49m\u001b[43mscheduling_strategy\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    398\u001b[0m \u001b[43m    \u001b[49m\u001b[43mworker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdebugger_breakpoint\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    399\u001b[0m \u001b[43m    \u001b[49m\u001b[43mserialized_runtime_env_info\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;132;43;01m{}\u001b[39;49;00m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    400\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    401\u001b[0m \u001b[38;5;66;03m# Reset worker's debug context from the last \"remote\" command\u001b[39;00m\n\u001b[0;32m    402\u001b[0m \u001b[38;5;66;03m# (which applies only to this .remote call).\u001b[39;00m\n\u001b[0;32m    403\u001b[0m worker\u001b[38;5;241m.\u001b[39mdebugger_breakpoint \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mb\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "\n",
    "# Let's start Ray\n",
    "ray.init()\n",
    "\n",
    "SAMPLES = 1000000; \n",
    "# By adding the `@ray.remote` decorator, a regular Python function\n",
    "# becomes a Ray remote function.\n",
    "@ray.remote\n",
    "def pi4_sample():\n",
    "    in_count = 0\n",
    "    for _ in range(SAMPLES):\n",
    "        x, y = random(), random()\n",
    "        if x*x + y*y <= 1:\n",
    "            in_count += 1\n",
    "    return in_count\n",
    "\n",
    "# To invoke this remote function, use the `remote` method.\n",
    "# This will immediately return an object ref (a future) and then create\n",
    "# a task that will be executed on a worker process. Get retreives the result. \n",
    "future = pi4_sample.remote()\n",
    "pi = ray.get(future) * 4.0 / SAMPLES\n",
    "print(f'{pi} is an approximation of pi') \n",
    "\n",
    "# Now let's do this 100,000 times. \n",
    "# With regular python this would take 11 hours\n",
    "# Ray on a modern laptop, roughly 2 hours\n",
    "# On a 10-node Ray cluster, roughly 10 minutes \n",
    "BATCHES = 100000\n",
    "results = [] \n",
    "for _ in range(BATCHES):\n",
    "    results.append(pi4_sample.remote())\n",
    "output = ray.get(results)\n",
    "pi = sum(output) * 4.0 / BATCHES / SAMPLES\n",
    "print(f'{pi} is a way better approximation of pi') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5542961e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:21,608\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(4845913810e67b7effffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:21,936\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(63a8710a27569f0dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:22,630\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(aa4d13694f93b9e8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:22,781\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(2d43834f00f3ecd8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,005\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9673d45474e93600ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,021\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(8b7acfbafa51083dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,082\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(263d5fdae06963eaffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,084\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(e1c8e5275b746f45ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,188\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(0da162a161990d45ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,360\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(5a939e23a9ff3a09ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,685\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(fedcd862f8b21bdaffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:23,889\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(11e8eb0b985ea3eeffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:23,919\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(2de30fb79905fbd2ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:24,088\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(1bfa5d4e4b381c3dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:24,686\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(cb5fa65dd93211f1ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:24,898\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(69f768ef89349d6effffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:25,754\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(00abef7dce70e143ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:25,943\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9fcb74a9409f5448ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:26,088\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(bb8322b8e4ecb546ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:26,091\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(1c0430bf1299080bffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:26,205\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(91ec2cea3b41f5b8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:26,221\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(fcd3a9249aa31c51ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:26,771\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(413e394227112558ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:27,778\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9fcfbf277e7aba4dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:28,825\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(e807df4edf7d6a52ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:29,882\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(8ae6f8bfbcc86243ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:31,919\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(cb256182bd462d8cffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:32,941\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9514e126175b9c29ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:33,082\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(59fb9f8ac44b6cf2ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:33,244\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(5e53e453487b0996ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:33,288\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d97f62d0863d6887ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:33,958\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(71f0987283edf8f7ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:33,963\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(b35cda6c3ba6c58affffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:35,001\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3bc0f941dca47a76ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:35,998\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(0717aca8c5953c86ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:37,049\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(01e4d079e2fb4cd3ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:37,166\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9e7f2e470956493fffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:37,241\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(ceacc1cbdd4b549dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,025\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(aa80cabfb996cb65ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,138\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d8ef22580d71c027ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,256\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(f6eaf069652f37d6ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,336\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(0a5cfbe7b41075eaffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,336\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(708ec91b498ea832ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,364\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(8ffcc0a25c1b869dffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:38,396\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(84f612c1e8cb7e05ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,424\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(5480026c0420da09ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,440\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3cb15384c09c853fffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,482\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(399f5a72caf20f8bffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,577\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(c577b46603f722f6ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,682\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3f2c1be0f13cd234ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,710\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(f31e41dcc2fcbb75ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,726\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(7305f06dcdf9d199ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,866\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(705ce38520b9d722ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,898\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3d55d0ee910d478affffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:38,962\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(07e452a767aba1a1ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:39,018\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(e6d4cbe9ecd13cfaffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:39,034\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d090a48c7126f1ffffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:39,114\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3f7a099a16bab56dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:39,182\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(b2b254933a7af291ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:40,182\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(a7f271f40ee52c58ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:41,194\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(6440e7b951dd253effffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:41,303\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(59c72fc0ac028bc3ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:43,225\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(714d25108b4f8913ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:43,442\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(e697c0165fb24727ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:45,258\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(72133c8e1ae430c1ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:46,322\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d2c1ea27b22746abffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:46,327\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(59f3b73c1dde2befffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:46,399\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(81e0f480f2fbff86ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:47,296\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(48e44ab148cea2f3ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:48,307\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(048c37d41686f54affffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:48,424\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(1184155a4a36df15ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:50,336\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(8c12ffd3e46fcb03ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:50,458\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(b81371cd282cfb5cffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:50,554\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(996ec310db66452effffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:50,585\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(714e9f40593b6ad5ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:51,341\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(262203f418c9d6cfffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:53,386\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(abb5e058005b4bb2ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:53,556\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(7a66ffa7e7ae63ceffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:53,657\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3d55d40958d394dbffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:54,433\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d7d72d80c8e223b8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:54,552\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(18792d1307c47776ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,432\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(dd8e0eb7a18f17caffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,506\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(eedc09537f853254ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,660\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(24e6ecf615bf9af6ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,677\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(c97fbe24ac1d38b5ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,721\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(37c36c0964753e30ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,723\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(fdc5e151827514d9ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,737\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(ea5b1554f4ad9caaffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:55,782\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(dccbb5abc0ffb12dffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,835\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(38096d15dda51dacffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,938\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(85b7204339046b65ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:55,954\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d4d33e9c9b34cbd4ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,001\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(259de272446e0c37ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,003\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(fa66adec8288eb73ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,048\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(7148aabd6e5c42a8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,139\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(a858eff4bb1b1f21ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,280\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(ea8c20db5c34b870ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,388\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(6ae0162aa3583c28ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,403\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(f2c58ed96a5130e6ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:56,433\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=25644, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3ec0e711793102f5ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,479\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3b8a4f5f17a92476ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,494\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=23728, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(c6e858b425493770ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,540\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(0c1eb4073babb192ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,572\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(b9d20906f0732496ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,651\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(211a878d98497baeffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,653\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(a90df6926e99f94bffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,743\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(249204a674cbb2a8ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,774\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(02cb6f158679e06effffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,866\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=22484, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(daf6dd150e076808ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:56,898\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(dec6f2ecab076731ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:07:56,991\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(e4968836ae03d4baffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:59,018\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=29248, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(33ac214c7df963f1ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:59,190\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=13228, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(2649f2d2990d241cffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:07:59,338\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=9720, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(f28f6d8a12250a5bffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:02,032\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(b8808587f2c1edd3ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:03,033\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(3d092722346787d3ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:03,035\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(0d00908f31d7f65affffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:03,038\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9372812269942954ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:04,040\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(232d85bc2ace34ddffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:04,043\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4636, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(95bf478df529d802ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:04,045\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2080, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(d43e6df58ae37cf3ffffffffffffffffffffffff01000000) was cancelled\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-03-10 19:08:04,048\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=4372, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 13, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(8e9a10c87c4f5626ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:04,051\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=2072, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(f15b90b46b6b9f3fffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:04,054\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26576, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 12, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(1ba9390d65110a3affffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 19:08:05,040\tERROR worker.py:399 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::pi4_sample()\u001b[39m (pid=26092, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1072, in ray._raylet.execute_task_with_cancellation_handler\n",
      "  File \"python\\ray\\_raylet.pyx\", line 805, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 850, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 857, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 861, in ray._raylet.execute_task\n",
      "  File \"C:\\Users\\rober\\AppData\\Local\\Temp\\ipykernel_32404\\898370870.py\", line 11, in pi4_sample\n",
      "ray.exceptions.TaskCancelledError: Task: TaskID(9ebf6124b8880348ffffffffffffffffffffffff01000000) was cancelled\n",
      "2023-03-10 21:07:21,609\tWARNING worker.py:1866 -- The node with node id: 803e9af4c1ab9bdbcd1189aa17fd784fe22e66e45f45b50e6884152d and address: 127.0.0.1 and node name: 127.0.0.1 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a \t(1) raylet crashes unexpectedly (OOM, preempted node, etc.) \n",
      "\t(2) raylet has lagging heartbeats due to slow network or busy workload.\n"
     ]
    }
   ],
   "source": [
    "for i in results:\n",
    "    ray.cancel(i) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0b5e2ad",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
